# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ../../hardware/cpu/amd
      ../../hardware/gpu/amd
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  # boot.kernelModules = [
  #   "amdgpu"
  # ];
  boot.extraModulePackages = [ ];
  # boot.kernelParams = [ "amd_pstate=active" ];

  # Enable OpenGL
  hardware.graphics = {
    # enable = true;
    # driSupport = true;
    # driSupport32Bit = true;
    extraPackages = with pkgs; [
      # amdvlk # AMD Open Source Driver for Vulkan®
      libvdpau-va-gl # VDPAU driver with OpenGL/VAAPI backend. H.264 only.
      # vaapiVdpau # VDPAU driver for the VAAPI librar. Code has not been touched for years.
    ];
    extraPackages32 = with pkgs; [
      # driversi686Linux.amdvlk
      driversi686Linux.libvdpau-va-gl # VDPAU driver with OpenGL/VAAPI backend. H.264 only.
      # driversi686Linux.vaapiVdpau # VDPAU driver for the VAAPI librar. Code has not been touched for years.
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8254c427-8d99-43b5-9ee3-73058feed1b6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7D78-0F91";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];
}
