# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ../../hardware/cpu/amd
      ../../hardware/gpu/amd
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Enable OpenGL
  hardware.graphics = {
    # enable = true;
    # driSupport = true;
    # driSupport32Bit = true;
    extraPackages = with pkgs; [
      # amdvlk # AMD Open Source Driver for Vulkan®
      libvdpau-va-gl # VDPAU driver with OpenGL/VAAPI backend. H.264 only.
      # vaapiVdpau # VDPAU driver for the VAAPI librar. Code has not been touched for years.
    ];
    extraPackages32 = with pkgs; [
      # driversi686Linux.amdvlk
      driversi686Linux.libvdpau-va-gl # VDPAU driver with OpenGL/VAAPI backend. H.264 only.
      # driversi686Linux.vaapiVdpau # VDPAU driver for the VAAPI librar. Code has not been touched for years.
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d8ed70d3-b853-41ff-98ca-de42ddae104b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ef64ea49-a36c-4421-b169-92643f04df9f".device = "/dev/disk/by-uuid/ef64ea49-a36c-4421-b169-92643f04df9f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DF26-4A0E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];
}
