# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ../../hardware/cpu/amd
      ../../hardware/gpu/amd
      ../../hardware/display/HiDPI.nix
      ../../hardware/display/OLED.nix
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelPackages = pkgs.linuxPackages_6_9;
  # boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = [ "amd_pstate=guided" ];
  # boot.kernelParams = [ "amd_pstate=active" ];
  boot.extraModulePackages = [ ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d8ed70d3-b853-41ff-98ca-de42ddae104b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ef64ea49-a36c-4421-b169-92643f04df9f".device = "/dev/disk/by-uuid/ef64ea49-a36c-4421-b169-92643f04df9f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DF26-4A0E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];
}
